spring:
  application:
    name: nuri-local
  config:
    import:
      - optional:file:env/local.env[.properties]

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


  graphql:
    schema:
      locations: classpath:graphql/**
    graphiql:
      enabled: true
    cors:
      allowed-origins: ${FRONTEND_URL}

oauth2:
  provider:
    google:
      baseUrl: ${GOOGLE_BASE_URL}
      clientId: ${GOOGLE_CLIENT_ID}
      redirectUrl: ${GOOGLE_REDIRECT_URL}
      client-secret: ${GOOGLE_CLIENT_SECRET}
    tiktok:
      baseUrl: ${TIKTOK_BASE_URL}
      clientId: ${TIKTOK_CLIENT_ID}
      redirectUrl: ${TIKTOK_REDIRECT_URL}
    kakao:
      baseUrl: ${KAKAO_BASE_URL}
      clientId: ${KAKAO_CLIENT_ID}
      redirectUrl: ${KAKAO_REDIRECT_URL}
    facebook:
      baseUrl: ${FACEBOOK_BASE_URL}
      clientId: ${FACEBOOK_CLIENT_ID}
      redirectUrl: ${FACEBOOK_REDIRECT_URL}
  new-user:
    front-redirect-url: ${NEW_USER_FRONT_REDIRECT_URL}
    caching-time: ${USER_INFO_CACHING_TIME}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

front-url:
  ${FRONTEND_URL}