spring:
  application:
    name:
      Nuri_Server

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update


  graphql:
    schema:
      locations: classpath:graphql/**
    graphiql:
      enabled: true
    cors:
      allowed-origins: ${FRONTEND_URL}