spring:
  application:
    name: nuri-prod
  config:
    import:
      - optional:file:/home/deploy/env/prod.env[.properties]

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  graphql:
    schema:
      locations: classpath:graphql/**
    cors:
      allowed-origins: ${FRONTEND_URL}

oauth2:
  provider:
    google:
      base-url: ${GOOGLE_BASE_URL}
      client-id: ${GOOGLE_CLIENT_ID}
      redirect-url: ${GOOGLE_REDIRECT_URL}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      grant-type: ${GOOGLE_GRANT_TYPE}
    tiktok:
      base-url: ${TIKTOK_BASE_URL}
      client-id: ${TIKTOK_CLIENT_ID}
      redirect-url: ${TIKTOK_REDIRECT_URL}
      client-secret: ${TIKTOK_CLIENT_SECRET}
      grant-type: ${TIKTOK_GRANT_TYPE}
    kakao:
      base-url: ${KAKAO_BASE_URL}
      client-id: ${KAKAO_CLIENT_ID}
      redirect-url: ${KAKAO_REDIRECT_URL}
      client-secret: ${KAKAO_CLIENT_SECRET}
      grant-type: ${KAKAO_GRANT_TYPE}
    facebook:
      base-url: ${FACEBOOK_BASE_URL}
      client-id: ${FACEBOOK_CLIENT_ID}
      redirect-url: ${FACEBOOK_REDIRECT_URL}
      client-secret: ${FACEBOOK_CLIENT_SECRET}
      grant-type: ${FACEBOOK_GRANT_TYPE}
  new-user:
    caching-time: ${USER_INFO_CACHING_TIME}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

front-url:
  ${FRONTEND_URL}