spring:
  application:
    name: nuri-dev

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  graphql:
    schema:
      locations: classpath:graphql/**
    cors:
      allowed-origins: ${FRONTEND_URL}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

session:
  chat-expiration: ${CHAT_EXPIRATION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

web:
  front-url: ${FRONTEND_URL}

chat:
  broadcast-threshold: ${BROADCAST_THRESHOLD}