spring:
  application:
    name: nuri-local
  config:
    import:
      - optional:file:env/local.env[.properties]

  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


  graphql:
    schema:
      locations: classpath:graphql/**
    graphiql:
      enabled: true
    cors:
      allowed-origins: ${FRONTEND_URL}

oauth2:
  provider:
    google:
      base-url: ${GOOGLE_BASE_URL}
      client-id: ${GOOGLE_CLIENT_ID}
      redirect-url: ${GOOGLE_REDIRECT_URL}
      client-secret: ${GOOGLE_CLIENT_SECRET}

    tiktok:
      base-url: ${TIKTOK_BASE_URL}
      client-id: ${TIKTOK_CLIENT_ID}
      redirect-url: ${TIKTOK_REDIRECT_URL}
    kakao:
      base-url: ${KAKAO_BASE_URL}
      client-id: ${KAKAO_CLIENT_ID}
      redirect-url: ${KAKAO_REDIRECT_URL}
  new-user:
    front-redirect-url: ${NEW_USER_FRONT_REDIRECT_URL}
    caching-time: ${USER_INFO_CACHING_TIME}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

front-url:
  ${FRONTEND_URL}